---
title: "test bootstrap method"
author: "Lukas Stammler"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
```

```{r}
daten <- runif(100, min = 1, max = 10)
mean(daten)

means <- vector()
rep <- 100000
for (i in 1:rep){
  sampl <- sample(daten, size = 100, replace = TRUE)
  means[i] <- mean(sampl)
}

hist(means)
CI <- mean(means) + c(-1, 1) * 1.96 * sd(means)
se <- sd(means)
CI
se

# https://pages.stat.wisc.edu/~larget/stat302/chap3.pdf
boot.mean = function(x,B,binwidth=NULL) {
n = length(x)
boot.samples = matrix( sample(x,size=n*B,replace=TRUE), B, n)
boot.statistics = apply(boot.samples,1,mean)
se = sd(boot.statistics)
require(ggplot2)
if ( is.null(binwidth) )
binwidth = diff(range(boot.statistics))/30
p = ggplot(data.frame(x=boot.statistics),aes(x=x)) +
geom_histogram(aes(y=..density..),binwidth=binwidth) + geom_density(color="red")
plot(p)
interval = mean(x) + c(-1,1)*1.96*se
print( interval )
return( list(boot.statistics = boot.statistics, interval=interval, se=se, plot=p) )
}

boot.mean(daten, B = 100000)
```

